name: update spotify data
on:
  schedule:
    # weekly
    - cron: "0 0 * * *"
  # support manual trigger
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: advanced-computing/alexa_giulio_rep
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run update script
        run: python Spotify_Data_Load.py