name: update spotify data
on:
  schedule:
    # weekly
    - cron: "0 0 * * *"
  # support manual trigger
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run update script
        env:
          GCP_SERVICE_ACCOUNT: ${{secrets.GCP_SERVICE_ACCOUNT}}
          KAGGLE_USERNAME: ${{secrets.KAGGLE_USERNAME}}
          KAGGLE_KEY: ${{secrets.KAGGLE_KEY}}
        run: python spotifydataload.py
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:." >> $GITHUB_ENV
      - name: Run tests
        run: pytest --cov=spotifydataload tests/

