KAGGLE_USERNAME = "alexashuetkaychan"
KAGGLE_KEY = "84bfb4133ffe7bbd8e0f0d1d4d14b20f"

[gcp_service_account]
type = "service_account"
project_id = "sipa-adv-c-alexa-giulio"
private_key_id = "18bfa6506f355fbbb06223b76cf93b4d0bbdc26e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8E+V2MmQJGWco
Q+1k6JROA2fBcDILa2ZjnUDAbvzk20wWtuiPwVx/VACDH6vXboKojLVKVxmzSxCx
Rk3ISTPK1gI6gDb8l5VG0KU7FbOYAOUMd0IBLvJVmui8dhBNv2Lfuu6botoGHdzh
i+j0aJ5Bf0SFMaIBhgWajf8LW8Jt4D4xHV386sxZvpYseBOGoB5WZkEoYTV0s2Ez
wMpz6j0mTFZoI/rebwfw7t/hvTelx6Q/2jONrbB1ICMhKFIxa7o8ixOc3EeZD8st
iLhW+Rp+aG5c2zKpkEV5jlvtyGEKGVI5IbxXie41yOtIQAjMdPdG2pjo0UF53NSn
wlkgjybtAgMBAAECggEAFNMdJqO4uNsztV0kFXa9KRAudlgual5HdYMtbsE7RjnT
6HXzNSujSsPp1Jr2o4FsfS4rSqJvSY9nt0FCDomwbuaYU5Lrw7cjA7bJfMvP2WZL
9j/kMo5YrcrbtzZZYspsr7oafmgfPOskkGK19g35a+YkF51hw0psJ2tOkJrl4dVw
Fl/eYfrI9bt4ariJ1UVXe95i/GTqNQdfiyFeu/Czw8S0C8F9+5HX/M4MRsM0i3V6
OPEo/GJGh9rr5QSNSu9zf2b2vgoPwFsewLsaF1HkbcDwnxHRTg750DhEPrpWaRzy
wA1du+KLsP9sH4QoGqs3NKJcipvTXfgT0iybdhGA4QKBgQD1q969PIQBuosoBsaz
wp+abyszTVeR+AzCPq4RQDdF315a5qcO7xIVD/dEMc34lGeJfHa1G8mZNjU6Y3GG
xk/h5VxDXf0Wu4nXDucLy8YCYZTmWPKuXNkJ9q89unTB7zGke4vuQG0wQ0+hb6qT
r+hwOPqryr/vwvx0pi85/3VEHQKBgQDD/CcxnH/gdXN0s8wPfuKE9EVOxrP1721l
c/A+R6tJG2oZef1qekLyQZOknpP8s+va0sq9WGSUMsiOdwj3JZVdb0eS8t7qgT0Z
ZZmMbNxIOkVhUG4RnOl5UAg4Ctdmd4RAHKg+5xsQRL1fQysokBfUeofhy0XwMY9m
b4X5ukhVEQKBgQDGilPEU3fLfdqgSnmjJRKfWGBtYX/386M8CDPctSz2RwKWK/mu
0/6lDvYiIq32ytix/+hfjUlrjKePvHYvGW3NffMGbprvGDjZmK2YluI7YmlXj2Lx
DxBIQRh2po1dfdV8vGvl7CNR8dQU/423NV5/80yCMaTUO5yTGQrpsE4w8QKBgEFG
hrdbbKwR8nZ4PAsdM80cnsjyHZZYPJOB3g6gSEh9PQVnQCRqvEl71fUKbDfKpU+o
zaXq/vTtRSdONko61ljca3ZiNiTdDsCaul2vFF9qKRmUdFShcpHZOiOQWNXkEMRZ
xx/MUZNFkd1cvc8wzv8SIJfv4Edz+lMf6fuXM+hBAoGBAOr55VRho6U63tHpXVOe
mmLqgz3E7ZeKGYDgeg2vKjjJ2EX9P81WEbid9IbaIVCoENTyAmRYx3QFOFLPfQmn
77+LvW50Z+GcAUI7u4IbP57efX/H2b9y10xjYPkfQT/LwiRdnkgqmJMhhFGLUsM7
iRnsAaeWw9rb5lKiWdlyConW
-----END PRIVATE KEY-----"""
client_email = "streamlit@sipa-adv-c-alexa-giulio.iam.gserviceaccount.com"
client_id = "111342525001616934840"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit@sipa-adv-c-alexa-giulio.iam.gserviceaccount.com"